apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgC0goxus3WCElkh7IjAmTP3ULP/eO88R9KsRq/P8sLPdEKMdpEE6RsxNyxOH2kBU8djSxVyZyTifpTDaezgpx3S3DtTQtZFOjYlOk5uub2dfvlc/2AHc/cpVbmFqZ/t0lXIHlFUQdryyNgH5l4kSVx6FZEQqHODB/bqBgZPhdgqLLWDjZfHIoy81wPZNbKWB7fg1oZro5pcFd9C50SMOTr7FkbvKFHEFy5jzhjq2Fn/D1EVADckFWhJVQBUS+a0rO3XuduEVpgpbvMsvUXopWBkK4eaKTYLFXu1VdHZIbSa3utxOmm4gu21dFNBMuQOq8q73mPe53eGs8PHMNQqWkiyENJaahqS69YipdNMZVJrJR779AfBk/EUIKJzQw83rFQbuztLbDDjztEG2R4qrv+0+/A5/DBfiK1X23etuM3zbgo8kZ8CRa2q0SmHwerilTwp6Gcje/ZqUbGLRG4opbw7bo3osjpBwBf4byxB7ZtPUpQBt1ri8XZSE2UEq+YRumLHNFb+0/VoA/clmETHvorUze21Kek5/s4p2rruCkvQp9norDrumXbE7sDtJ9p8CwgXIfMaq/9RcGst1X43FNnGiJiKHR94nvijJF2vvkHrLcsJNPXGfaIgQ13QP552zM9mwMHsrrCrhy6znhYeHp5fQhe66Orqxo6gbMnYJjaeyr4RkLKIszBs64SZLFaUGU3FZpxgCNMvxUvBC61Paznpc5efJbAlBIS+D88vzNuS3HMGbVaNNHUjy7tc9R/2b3ocWyte0vwPDYy742JmsRHAjdb096E4rbzDndX88nIRaaA6o8ftC/VdN5YbeUh9mX4MG/Qneyd/Fd+Cs3f+FhnVwsuh0hbLFhHdFUK9P4TsSMm0BGVJuHa99+xHdeIF0ZcD6pFn0ISvB2gLsjUgPoA5T8wCceFHTfXIrfam55p1z3nHgUJP1mSF2Dlg0HEe6EHoThcoEn/zkcyebLy0tQctQsdr9v5zgKjxk+0Gt+M2u31pysjKcOsZ4r36Gzwuoh7i6E7nGtV3gcsEyaBn310kria5ONWijNgirwTKBQWr8xLzplZ2+SAS3YXKBfHAvFPcdIOYKyNB5fZdTMq7xcKHMZScCTK1IYB3HLxmvbmfYB5jFEuUIO/+yDooq7bYmNf5IEJMXWp/4VcZUjvGiv53fNR0oxrUUnKD8jJbugyvTHudZmZSm+8glyMepNagyI+6SD63wVoRi1EP3MFgzfNcq0AgE7ejDqxZhGlwumvfPimLk7uJFeEMSTSsbFMtu1c7Dp3AbI8hqEj/1VI2pLu2O22i8PfPcPyp1/TzUQnQ+rcFK6e8oV8+Q05qRKXl5opX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

