apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-gitops-cp4d-instance
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-cp4d-instance/namespace
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp4d-instance
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
